# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "06bce1d5cf06a3c7aac4ceb8e75ec195"
name = "test-app-01"
application_url = "https://arturo-multilobed-tasia.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"


[[webhooks.subscriptions]]
topics = ["inventory_levels/update"]
uri = "/webhooks/app/inventory_levels/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products,read_products,write_orders,read_orders,write_customers,read_customers,read_all_orders,read_inventory,write_inventory,read_locations"

[auth]
redirect_urls = ["https://arturo-multilobed-tasia.ngrok-free.dev/api/auth"]
